### ISSUE TITLE
topaz run command is failing to pull the policy image

### ISSUE THREAD

**Issue by US-Thakur** [aserto-dev/topaz#120]
Hey folks,  I am trying to run topaz in a container on EKS using docker-in-docker method. To run a sample app I am following [this example ](https://github.com/aserto-dev/topaz/tree/main#create-a-configuration)

a) `topaz configure -d -s -r ghcr.io/aserto-policies/policy-todo-rebac:latest -n todo`
This generates the topaz config.yaml which I have added at the end.

b) `topaz run` then fails with below error:
```
bundle error: failed to pull ghcr.io/aserto-policies/policy-todo-rebac:latest: download for 'ghcr.io/aserto-policies/policy-todo-rebac:latest' failed: failed to resolve ghcr.io/aserto-policies/policy-todo-rebac:latest: failed to do request: Head \"https://ghcr.io/v2/aserto-policies/policy-todo-rebac/manifests/latest\": x509: certificate is not valid for any names, but wanted to match ghcr.io
```
Adding the full log at the end. Also I am attaching the k8s config of the sample deployment in case if its relevant.

I am using latest topaz CLI and policy0.2.3 CLI. I can pull the images from docker repo using `docker pull` command though.

Any help to get past this issue is highly appreciated folks.

```
---
# config schema version
version: 1 

logging:
  prod: true
  log_level: info

directory:
  db_path: ${TOPAZ_DIR}/db/directory.db
  seed_metadata: true

# remote directory is used to resolve the identity for the authorizer.
remote_directory:
  address: "0.0.0.0:9292" # set as default, it should be the same as the reader as we resolve the identity from the local directory service.
  insecure: true

# default jwt validation configuration
jwt:
  acceptable_time_skew_seconds: 5 # set as default, 5 secs

api:
  reader:
    grpc:
      listen_address: "0.0.0.0:9292"
      # if certs are not specified default certs will be generate with the format reader_grpc.*
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
    gateway:
      listen_address: "0.0.0.0:9393"
      # if not specified, the allowed_origins includes localhost by default
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      # if no certs are specified, the gateway will have the http flag enabled (http: true)
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"
      http: false
      read_timeout: 2s # default 2 seconds
      read_header_timeout: 2s 
      write_timeout: 2s 
      idle_timeout: 30s # default 30 seconds
    health:
      listen_address: "0.0.0.0:9494"
  writer:
    grpc:
      listen_address: "0.0.0.0:9292"
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
    gateway:
      listen_address: "0.0.0.0:9393"
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"
      http: false
      read_timeout: 2s
      read_header_timeout: 2s
      write_timeout: 2s
      idle_timeout: 30s
    health:
      listen_address: "0.0.0.0:9494"
  exporter:
    grpc:
      listen_address: "0.0.0.0:9292"
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
    gateway:
      listen_address: "0.0.0.0:9393"
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"
      http: false
      read_timeout: 2s
      read_header_timeout: 2s
      write_timeout: 2s
      idle_timeout: 30s
    health:
      listen_address: "0.0.0.0:9494"
  importer:
    grpc:
      listen_address: "0.0.0.0:9292"
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
    gateway:
      listen_address: "0.0.0.0:9393"
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"
      http: false
      read_timeout: 2s
      read_header_timeout: 2s
      write_timeout: 2s
      idle_timeout: 30s
    health:
      listen_address: "0.0.0.0:9494"
  
  authorizer:
    needs:
      - reader
    grpc:
      connection_timeout_seconds: 2
      listen_address: "0.0.0.0:8282"
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
    gateway:
      listen_address: "0.0.0.0:8383"
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      certs:
        tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
        tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
        tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"
      http: false
      read_timeout: 2s
      read_header_timeout: 2s
      write_timeout: 2s
      idle_timeout: 30s
    health:
      listen_address: "0.0.0.0:8484"

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  # max_plugin_wait_time_seconds: 30 set as default
  local_bundles:
    paths: []
    skip_verification: true
  config:
    services:
      ghcr:
        url: https://ghcr.io
        type: "oci"
        response_header_timeout_seconds: 5
    bundles:
      todo:
        service: ghcr
        resource: "ghcr.io/aserto-policies/policy-todo-rebac:latest"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120
```

```
root@dind-and-docker-cmds-67fdfdcbb6-2tk8d:/# topaz run
>>> starting topaz...
{"level":"info","component":"config","time":"2023-08-17T16:51:01Z","message":"setting up certs for authorizer"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2023-08-17T16:51:01Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"config","time":"2023-08-17T16:51:01Z","message":"setting up certs for importer"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2023-08-17T16:51:01Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"config","time":"2023-08-17T16:51:01Z","message":"setting up certs for reader"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2023-08-17T16:51:01Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"config","time":"2023-08-17T16:51:01Z","message":"setting up certs for writer"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2023-08-17T16:51:01Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"config","time":"2023-08-17T16:51:01Z","message":"setting up certs for exporter"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key","/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2023-08-17T16:51:01Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"edge-ds","component":"directory","component":"kvs","db_path":"/db/directory.db","time":"2023-08-17T16:51:01Z","message":"opening boltdb store"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","current":"0.0.0","required":"0.0.2","time":"2023-08-17T16:51:01Z","message":"begin schema migration"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","next":"0.0.1","time":"2023-08-17T16:51:01Z","message":"starting"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","next":"0.0.1","time":"2023-08-17T16:51:01Z","message":"finished"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","current":"0.0.1","time":"2023-08-17T16:51:01Z","message":"updated current version"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","next":"0.0.2","time":"2023-08-17T16:51:01Z","message":"starting"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","next":"0.0.2","time":"2023-08-17T16:51:01Z","message":"finished"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","current":"0.0.2","time":"2023-08-17T16:51:01Z","message":"updated current version"}
{"level":"info","component":"edge-ds","component":"directory","component":"migrate","current":"0.0.2","required":"0.0.2","time":"2023-08-17T16:51:01Z","message":"finished schema migration"}
{"level":"info","name":"ds.identity","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.user","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.object","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.relation","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.graph","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.check_relation","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","name":"ds.check_permission","time":"2023-08-17T16:51:01Z","message":"registering builtin1"}
{"level":"info","component":"runtime","instance-id":"-","time":"2023-08-17T16:51:01Z","message":"creating OPA plugins manager"}
{"level":"info","plugin-name":"aserto_decision_log","time":"2023-08-17T16:51:01Z","message":"registering plugin"}
{"level":"info","plugin-name":"aserto_edge","time":"2023-08-17T16:51:01Z","message":"registering plugin"}
{"level":"info","component":"runtime","instance-id":"-","name":"todo","plugin":"bundle","time":"2023-08-17T16:51:01Z","message":"Starting bundle loader."}
{"level":"info","log-source":"logrus","time":"2023-08-17T16:51:01Z","message":"trying next host"}
{"level":"error","component":"runtime","instance-id":"-","name":"todo","plugin":"bundle","time":"2023-08-17T16:51:01Z","message":"Bundle load failed: failed to pull ghcr.io/aserto-policies/policy-todo-rebac:latest: download for 'ghcr.io/aserto-policies/policy-todo-rebac:latest' failed: failed to resolve ghcr.io/aserto-policies/policy-todo-rebac:latest: failed to do request: Head \"https://ghcr.io/v2/aserto-policies/policy-todo-rebac/manifests/latest\": x509: certificate is not valid for any names, but wanted to match ghcr.io"}
{"level":"info","log-source":"logrus","time":"2023-08-17T16:51:01Z","message":"trying next host"}
{"level":"error","component":"runtime","instance-id":"-","name":"todo","plugin":"bundle","time":"2023-08-17T16:51:01Z","message":"Bundle load failed: failed to pull ghcr.io/aserto-policies/policy-todo-rebac:latest: download for 'ghcr.io/aserto-policies/policy-todo-rebac:latest' failed: failed to resolve ghcr.io/aserto-policies/policy-todo-rebac:latest: failed to do request: Head \"https://ghcr.io/v2/aserto-policies/policy-todo-rebac/manifests/latest\": x509: certificate is not valid for any names, but wanted to match ghcr.io"}
{"level":"info","log-source":"std","time":"2023-08-17T16:51:01Z","message":"2023/08/17 16:51:01 E30012 runtime loading failed: error loading plugins: 2 errors occurred:\n\t* bundle error: failed to pull ghcr.io/aserto-policies/policy-todo-rebac:latest: download for 'ghcr.io/aserto-policies/policy-todo-rebac:latest' failed: failed to resolve ghcr.io/aserto-policies/policy-todo-rebac:latest: failed to do request: Head \"https://ghcr.io/v2/aserto-policies/policy-todo-rebac/manifests/latest\": x509: certificate is not valid for any names, but wanted to match ghcr.io\n\t* bundle has never been activated\n\n"}
topaz: error: cmd.RunCmd.Run(): running "docker run -ti --rm --name topaz --platform=linux/amd64 -p 8282:8282 -p 8383:8383 -p 8484:8484 -p 9292:9292 -v /root/.config/topaz/certs:/certs:rw -v /root/.config/topaz/cfg:/config:ro -v /root/.config/topaz/db:/db:rw -v /root/.policy:/root/.policy:ro ghcr.io/aserto-dev/topaz:latest run --config-file /config/config.yaml" failed with exit code 1
root@dind-and-docker-cmds-67fdfdcbb6-2tk8d:/# 
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-and-docker-cmds
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind-and-docker-cmds
  template:
    metadata:
      labels:
        app: dind-and-docker-cmds
    spec:
      containers:
      - name: dind-daemon
        image: docker:dind
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        volumeMounts:
        - name: ca-certs
          mountPath: /certs/ca
        - name: client-certs
          mountPath: /certs/client
        - name: topaz-config
          mountPath: /root/.config
      - name: docker-cmds
        image: <custom_docker_image which has Topaz and Policy CLI>
        #image: docker:latest
        command: ["sleep", "10000"]
        env:
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        - name: DOCKER_HOST 
          value: tcp://127.0.0.1:2376
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: /certs/client
        volumeMounts:
        - name: client-certs
          mountPath: /certs/client
          readOnly: true
        - name: topaz-config
          mountPath: /root/.config
      volumes:
      - name: ca-certs
        emptyDir: {}
      - name: client-certs
        emptyDir: {}
      - name: topaz-config
        emptyDir: {}

```

**Comment by carabasdaniel** [comment]
Hi @US-Thakur,

Thanks for submitting this issue. This is a very interesting scenario. 

Could you please try to update the configuration manually to use http://ghcr.io for the OPA service configuration or add [allow_insecure_tls: true] (https://www.openpolicyagent.org/docs/latest/configuration) ? 

Can you pull the image from inside your DinD container ?
```
opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  # max_plugin_wait_time_seconds: 30 set as default
  local_bundles:
    paths: []
    skip_verification: true
  config:
    services:
      ghcr:
        url: http://ghcr.io
        type: "oci"
        response_header_timeout_seconds: 5
    bundles:
      todo:
        service: ghcr
        resource: "ghcr.io/aserto-policies/policy-todo-rebac:latest"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120
```
