### ISSUE TITLE
Docker Compose Documentation, Onboarding

### ISSUE THREAD

**Issue by expertonium** [aserto-dev/topaz#162]
Documentation leveraging docker-compose.yml and some surrounding context about files needed.  Includes watching for policy changes during development.  Does not address use of Directory.  I have found this helpful to our workflow, which heavily leverages docker-compose.

This may be a Docker MacOS issue, but changing `localhost` to `0.0.0.0` in the config was necessary to avoid Connection Reset errors.

Here's the approach.

---

Where `/docker-compose.yml` file content is

```
version: "3.5"
services:
  topaz:
    command:
      - run
      - --config-file
      - /configs/local.yaml
    container_name: topaz
    environment:
      - TOPAZ_POLICIES_PATH=/policies
    image: ghcr.io/aserto-dev/topaz:latest
    ports:
      - 8282:8282
      - 8383:8383
      - 8484:8484
      - 8585:8585
      - 9292:9292
    networks:
      - my-network
    volumes:
      - ./docker/shared-mount/topaz/configs:/configs
      - ./docker/shared-mount/topaz/policies:/policies
      - ./docker/shared-mount/topaz/certs:/certs
networks:
  my-network:
    driver: bridge
    name: my-network
```

Where `/docker/shared-mount/topaz/configs/local.yaml` file content is

```
# Examples: https://github.com/aserto-dev/topaz/tree/main/docs/examples
---
version: 2
logging:
  prod: true
  log_level: info

directory:
  db_path: ${TOPAZ_DIR}/db/directory.db
  seed_metadata: true
    
remote_directory:
  address: "0.0.0.0:9292"
  insecure: true
    
api:
  health:
    listen_address: "0.0.0.0:8484"
  services:
    authorizer:
      grpc:
        connection_timeout_seconds: 2
        listen_address: "0.0.0.0:8282"
        certs:
          tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
          tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
          tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
      gateway:
        listen_address: "0.0.0.0:8383"
        certs:
          tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
          tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
          tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: [${TOPAZ_POLICIES_PATH}]
    skip_verification: true
    watch: true
```

Where `/docker/shared-mount/topaz/policies/todoApp.GET.rego` file content is

```
package todoApp.GET.todos

default allowed = true
```

Where `/docker/shared-mount/topaz/certs/.gitkeep` file exists

Run `docker-compose up`
