### ISSUE TITLE
Topaz doesn't mount a volume for decision logs

### ISSUE THREAD

**Issue by ronenh** [aserto-dev/topaz#232]
Topaz can write decision logs to a local file using the `type: file` option in the `decision_logger` config section.
However, when using `topaz start` to run the container, that path isn't mounted from the local filesystem.
As a result, decision logs are written to a file inside the container but aren't visible in the host filesystem.

When file logging is enabled, `topaz start` should mount the path specified in `decision_logger.config.log_file_path`.

For example, with this config:
```
decision_logger:
  type: file
  config:
    log_file_path: "${TOPAZ_DIR}/decision_logs"
    max_file_size_mb: 20
    max_file_count: 3
```

`${TOPAZ_DIR}/decision_logs` should be mounted as a volume in the topaz container.
